server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  profiles:
    active: default
  cloud:
    config:
      server:
        git:
          uri: git@e.coding.net:cccy/spring_cloud_config_demo.git
          search-paths:
            - spring_cloud_config_demo
      label: master
  rabbitmq:
    host: ${settings.dev.server-addr}
    port: 5672
    username: guest
    password: guest
eureka:
  instance:
    instance-id: config-center3344
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
# 为了刷新配置能动态更新
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"