server:
  port: 80
spring:
  application:
    name: cloud-order-feign-hystrix-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka,http://localhost:7002/eureka
# 开启feign的hystrix支持
feign:
  hystrix:
    enabled: true

# 日志级别
logging:
  level:
    com.cccy.springcloud.service.PaymentFeignService: debug