server:
  port: 7777
spring:
  application:
    name: cloud-zipkin-server
eureka:
  instance:
    instance-id: cloud-zipkin-server7777
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka