server:
  port: 2003
spring:
  profiles:
    active: default
  application:
    name: cloud-alibaba-seata-account-service
  cloud:
    alibaba:
      seata:
        tx-service-group: default # 事务组名称
        # docker启动语句, 为了nacos注册, 手动指定一下SEATA_IP
        # docker run --network host --name seata-server -d -p 8091:8091 -e SEATA_IP=192.168.91.128 -e SEATA_CONFIG_NAME=file:/root/seata-config/registry -v /root/docker/seata:/root/seata-config seataio/seata-server
    nacos:
      discovery:
        server-addr: ${settings.dev.server-addr}:8848
#    sentinel:
#      transport:
#        dashboard: ${settings.dev.server-addr}:8858
#        port: 8719 # 客户端的端口 如果被占用则+1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seata_account?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cccy.springcloud.entity

management:
  endpoints:
    web:
      exposure:
        include: '*'